[package]
name = "state"
version = "0.1.0"
authors = ["Crush"]
edition = "2018"

[dependencies]
chrono = { version = "^0.4", features = ["serde"] }
clap = "^2.33"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
